- hosts: all
  become: yes
  max_fail_percentage: 0
  vars_files: ./variables.yaml
  tasks:
    - action: setup

    - import_tasks: zz_0-templates.yml
      vars:
         src: templates/resolv.conf.j2
         dest: /etc/resolv.conf


    - import_tasks: zz_0-add-packages.yml
      vars:
         package_list:
           - haproxy

    - import_tasks: zz_0-templates.yml
      vars:
         src: templates/haproxy.cfg.j2
         dest: /etc/haproxy/haproxy.cfg

    - import_tasks: zz_1-dns-update.yml
      become: no
      delegate_to: localhost
      vars:
        dnsrecord: "{{ endpoint }}"
        dnsvalue: "{{ vip_ip }}"
        dnstype: "A"

    - import_tasks: zz_0-restart_services.yml
      vars:
         svc:
           - haproxy
