#!/bin/bash
sudo cp /etc/hosts.ini /etc/hosts
virsh net-dhcp-leases default | awk '/k8s/{ print $5" "$6 }' | sed -e 's/\/24//' | sudo tee -a /etc/hosts
grep k8slb /etc/hosts | sed -e 's/k8slb/kubernetes.k8s.xprd.local/' | sudo tee -a /etc/hosts
