- hosts: all
  become: yes
  max_fail_percentage: 0
  gather_facts: yes
  vars_files: ./variables.yaml

  tasks:
     - import_tasks: zz_0-templates.yml
       vars:
         src: templates/resolv.conf.j2
         dest: /etc/resolv.conf

     - import_tasks: zz_0-templates.yml
       vars:
         src: templates/hosts.j2
         dest: /etc/hosts

     - import_tasks: zz_2-users.yml

     - import_tasks: zz_1-proxy-system.yml
       when: (proxy is defined) and (proxy|length > 5)

     - name: create containerd.service.d dir
       file:
          path: /etc/systemd/system/containerd.service.d
          state: directory
          owner: root
          group: root
          mode: u=rw,g=r,o=r
       when: (proxy is defined) and (proxy|length > 5)
     
     - name: create http-proxy.conf for containerd
       copy:
          dest: /etc/systemd/system/containerd.service.d/http-proxy.conf
          content: |
             [Service]
             Environment="HTTP_PROXY=http://{{ proxy }}"
             Environment="HTTPS_PROXY=http://{{ proxy }}"
             Environment="NO_PROXY=localhost,{{ masters }},{{ k8swk1_ip }},{{ k8swk2_ip }},{{ k8swk3_ip }},{{ podscidr }},{{ svcscidr }}"
       when: (proxy is defined) and (proxy|length > 5)

     - import_tasks: pre-requisites.yml

     - import_tasks: init_master.yml
       when: inventory_hostname in groups["main"]

     - import_tasks: join.yml


  handlers:
   - name: restart_containerd
     service:
       name: containerd
       state: restarted

   - name: update_apt_cache
     apt:
       update_cache: yes

